### PR TITLE
Prepare kern-6 release

### PR DESCRIPTION
**Pull request by Athanaseus**

### CODE REVIEW

**Comment by gijzelaerr** [comment]
nice! Did you run the update file though? it should generate a list of packages.

**Comment by Athanaseus** [comment]
ah no, I will do that.

**Comment by Athanaseus** [comment]
It prints the output on the console, should it be saved in a file?

**Comment by gijzelaerr** [comment]
yes to the package list HTML file :)

**Review by gijzelaerr — APPROVED** [review]

**Pull request merged**
